Feature/t28.backend tests
flowacademyhu/epsilon-sport-event-organizer pull request #58
Opened 2019-06-28 07:14 UTC by VicziTomi

2019-06-28 08:01 UTC, borosr approved these changes

2023-04-10 09:57 UTC, PumpkinSeed requested changes
LGTM

2023-04-10 09:58 UTC, PumpkinSeed approved these changes

2023-04-11 12:21 UTC, VicziTomi commented
Not sure if we really need this PR to be merged, but ok  thanks. Merged

2023-04-11 12:21 UTC, merged